"""Load and dump ``.lgrlw.toml`` project configuration."""

from __future__ import annotations

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - exercised only on Python 3.10
    import tomli as tomllib

from lgrlw.schemas import ProjectConfig


def load_config(path: Path) -> ProjectConfig:
    """Parse ``.lgrlw.toml`` and return a validated :class:`ProjectConfig`."""
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    project = data.get("project", {})
    return ProjectConfig.model_validate(project)


def dump_config(cfg: ProjectConfig, path: Path) -> None:
    """Write ``cfg`` to ``path`` as a small, deterministic TOML file.

    We intentionally do not use a third-party TOML writer: the schema is
    flat and fully controlled by us, so a hand-written emitter keeps the
    dependency set minimal and the output stable for diffing.
    """
    lines = [
        "# Research-Wiki project configuration.",
        "# Generated by `lgrlw init`. See docs/architecture.md for the schema.",
        "",
        "[project]",
        f'schema_version   = "{cfg.schema_version}"',
        f'direction        = "{_escape(cfg.direction)}"',
        f'kb_name          = "{_escape(cfg.kb_name)}"',
        f'workspaces_name  = "{_escape(cfg.workspaces_name)}"',
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


__all__ = ["dump_config", "load_config"]
